<?php

namespace ContainerXxKThnb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SLNq2ZtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SLNq2Zt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SLNq2Zt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'folderRepository' => ['privates', 'App\\Repository\\FolderRepository', 'getFolderRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'folderRepository' => 'App\\Repository\\FolderRepository',
            'em' => '?',
        ]);
    }
}
