<?php

namespace ContainerXxKThnb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValutControllerpatchValutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ORyGLnl.App\Controller\ValutController::patchValut()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ORyGLnl.App\\Controller\\ValutController::patchValut()'] = ($container->privates['.service_locator.ORyGLnl'] ?? $container->load('get_ServiceLocator_ORyGLnlService'))->withContext('App\\Controller\\ValutController::patchValut()', $container);
    }
}
