<?php

namespace ContainerWBlzz23;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFolderControllergetFoldersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KI0gtOV.App\Controller\FolderController::getFolders()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KI0gtOV.App\\Controller\\FolderController::getFolders()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'folderRepository' => ['privates', 'App\\Repository\\FolderRepository', 'getFolderRepositoryService', true],
        ], [
            'folderRepository' => 'App\\Repository\\FolderRepository',
        ]))->withContext('App\\Controller\\FolderController::getFolders()', $container);
    }
}
