<?php

namespace ContainerWBlzz23;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValutControllercreateValutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ORyGLnl.App\Controller\ValutController::createValut()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ORyGLnl.App\\Controller\\ValutController::createValut()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'valutRepository' => ['privates', 'App\\Repository\\ValutRepository', 'getValutRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'valutRepository' => 'App\\Repository\\ValutRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ValutController::createValut()', $container);
    }
}
