<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxKThnb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxKThnb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxKThnb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxKThnb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxKThnb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxKThnb',
    'container.build_id' => 'c5d955ed',
    'container.build_time' => 1749746290,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxKThnb');
